server:
  port: 8080

#security:
#  user:
#    name: admin
#    password: admin1234

spring:
  messages:
    encoding: UTF-8
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: true
  datasource:
    url: jdbc:mysql://localhost:3306/nanum
    username: root
    password: 1234
    driver-class-name: com.mysql.jdbc.Driver
  session:
    store-type: none



#---
#
#spring:
#  profiles: local
#  jpa:
#    hibernate:
#      ddl-auto: update
#  datasource:
#    url: jdbc:mysql://localhost:3306/nanum
#    username: root
#    password: admin1234
#  session:
#    store-type: none